services:
  - type: web
    name: zenhaven-frontend
    runtime: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false 